### ISSUE TITLE
prefix+y seems to depend on those arrow keys (the ones way over there...)

### ISSUE THREAD

**Issue by windowsrefund** [tmux-plugins/tmux-yank#29] opened 2015-01-03 12:40 UTC
but being a "home keys" kinda guy, this makes me sad. It would be better if the prefix+y functionality would yank the last command rather than the current command line. In other words, wouldn't it be nice to have:

$ true
$ 
prefix+y
$ true

It's also interesting to realize the current implementation of prefix+y does not copy a current commandline in bash after ctrl+p has been hit (a faster method than hitting the up arrow). This is just a side note however considering the above request. Having to ctrl+p or up arrow just to draft something for yanking purposes is wasteful since we can't assume we actually want to run the command again. In most cases, we're probably going to ctrl+u to clear the current command after yanking

Update: I've been pondering this in more detail and have to admit I myself, am not even clear on what I'd expect this feature to add to a sane workflow. Going off your database-driven example, I see the motivation but would argue one should never type raw commands into a database. Instead, the SQL should be written into a script which is then loaded. The script would then be scp'd over to production and loaded. For me, that's a best practice since it lends itself to repeatability, change control, and overall collabortation. So... if we take that motivation out of the mix, what problem(s) are we really trying to solve here? It would seem to me that we're trying to cross the boundries of tmux windows and/or panes since from within a single window or pane, we have things like !!, alt+., ctl+p/n at our disposal. Just thinking out loud...

**Comment by bruno-** [comment] 2015-02-14 23:47
Hey sorry I'm replying so late.

> In other words, wouldn't it be nice to have:

> $ true
> $ 
> prefix+y
> $ true

This feature looks nice and I'd be glad to have it if someone want's to implement it. But lets not override the existing `prefix+y` but instead map it to something else. (prefix + shift + y ?)

> It's also interesting to realize the current implementation of prefix+y does not copy a current commandline in bash after ctrl+p has been hit (a faster method than hitting the up arrow)

Hmm.. this seems to work for me with `ctrl+p`.. I use it all the time..
I'd appreciate more details on how to reproduce this.

**Comment by bruno-** [comment] 2015-03-14 22:31
Hey @windowsrefund, any updates on this?

**Comment by bruno-** [comment] 2015-06-17 08:22
Closing since it's been a long time since the issue was opened. Feel free to reopen the issue if someone wants to continue the discussion.

**Closed by bruno-** 2015-06-17 08:22 UTC
Labels: waiting for reply
